CREATE TABLE [dbo].[Game]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[Name] NVARCHAR(250) NOT NULL,
	[Genre] NVARCHAR(250) NOT NULL,
	[Price] FLOAT NOT NULL,
	[ReleaseDate] DATETIME NOT NULL
)
